### ISSUE TITLE
Autobuild pull requests

### ISSUE THREAD

**Issue by cjosu** [cancervariants/cancervariants.org#37]
We would like to automatically build PRs that are pending review, as described here [this](https://docs.readthedocs.io/page/guides/autobuild-docs-for-pull-requests.html). 

Looking into [Go Static App](https://www.gostaticapp.com/).

**Comment by ahwagner** [comment]
If this is not supported by GH natively, the current process of local build is good enough. The idea is to create a PR in a staging environment that reflects the production environment.

**Comment by cjosu** [comment]
Due to GitHub page limitations (one deployment environment per repository), the native solutions I've found involve creating an additional repository. It would not need to be maintained in parallel - basically an empty repository would accept the build and deploy to its own GH-page. 

But it doesn't seem like we want to go that route. I will reach out to Adam Herman before closing this in case he has any thoughts.

**Comment by cjosu** [comment]
Due to GitHub page limitations (one deployment environment per repository), the native solutions I've found involve creating an additional repository. It would not need to be maintained in parallel - basically an empty repository would accept the build and deploy to its own GH-page.

Unless we want to try something along those lines (or pending a better approach), I'll leave this closed.
