### ISSUE TITLE
Organizations page incomplete

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/cancervariants.org#4]
We are lacking organizations that are listed as participants in Table 1 of the VICC U24, as well as several Variant Interpretation Knowledgebases. Since these lists are largely redundant, we could just focus on the latter list.

@obigriffith @malachig thoughts?

Organizations:

- [ ] Institute for Research in Biomedicine, Barcelona, Spain
- [ ] Ohio State University (OSU) / James Cancer Hospital
- [ ] Washington University School of Medicine
- [ ] Synapse
- [ ] The Jackson Laboratory
- [ ] MSKCC
- [ ] Weill Cornell Medical College
- [ ] Illumina
- [ ] Dana-Farber Cancer Institute
- [ ] Molecular Match

Variant Interpretation Knowledgebases:
- [x] Cancer Genome Interpreter
- [ ] Cancer Driver Log (CanDL)
- [x] CIViC
- [ ] Gene-Drug Knowledge Database
- [x] JAX Clinical Knowledgebase
- [x] OncoKB
- [x] PMKB
- [ ] DoCM
- [ ] Basespace Knowledge Network
- [ ] MatchMiner
- [x] Molecular Match

**Comment by obigriffith** [comment]
Yeah. This sounds fine. Although, the key Knowledgebase Partners (people behind the knowledgebases) could also be added to the Members page.

**Comment by ahwagner** [comment]
closing this for capture in the new organizations collection and view referenced in #28
